version: "3.8"

services:
  app:
    build:
      args:
        user: "${COMPOSE_USER}"
        uid: "${COMPOSE_UID}"
      context: docker/app
    container_name: "${COMPOSE_NAME}.app"
    volumes:
      - ./:/var/www
    environment:
      - LC_ALL=es_ES.UTF-8
      - LANG=es_ES.UTF-8
      - LANGUAGE=es_ES.UTF-8

  nginx:
    build: docker/nginx
    container_name: "${COMPOSE_NAME}.nginx"
    ports:
      - ${NGINX_PORT}:80
    volumes:
      -  ./:/var/www

  cron:
    container_name: "${COMPOSE_NAME}.cron"
    build: docker/cron
    volumes:
      - ./:/app
      - ./cron/crontabs/:/var/spool/cron/crontabs/
    cap_add:
      - SYS_PTRACE
