{
 "title": "Estadísticas de ventas por día",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ventas diarias",
   "type": "barchart",
   "description": "Gráfico de cantidad de ventas por día",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "`library-erp`",
     "rawSql": "SELECT\n  DATE(created_at) AS fecha,\n  COUNT(*) AS total_ventas\nFROM\n  sales\nGROUP BY\n  DATE(created_at)\nORDER BY\n  fecha;\n"
    }
   ]
  },
  {
   "title": "Ventas del día por hora",
   "type": "timeseries",
   "description": "Gráfico de  cantidad de ventas del día por hora",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "`library-erp`",
     "rawSql": "SELECT \n  DATE_ADD(DATE(NOW()), INTERVAL HOUR(created_at) HOUR) AS timestamp,\n  COUNT(*) AS ventas\nFROM sales\nWHERE created_at >= CURDATE() AND created_at < CURDATE() + INTERVAL 1 DAY\nGROUP BY timestamp\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Productos más vendidos en el día",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "`library-erp`",
     "rawSql": "SELECT\n  p.name AS Producto,\n  SUM(cs.quantity) AS \"Total Vendido\"\nFROM content_sales cs\nJOIN sales s ON cs.sale_id = s.id\nJOIN products p ON cs.product_id = p.id\nWHERE s.created_at >= CURDATE() AND s.created_at < CURDATE() + INTERVAL 1 DAY\nGROUP BY cs.product_id, producto\nORDER BY \"Total Vendido\" DESC\nLIMIT 10;"
    }
   ]
  }
 ]
}